
FROM python:3.10.6

WORKDIR /app

COPY . /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

ENV DJANGO_SETTINGS_MODULE=moni.settings.local

CMD ["celery", "-A", "moni", "worker", "--loglevel=info"]
