name: Pre-commit

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  pre-commit:
    name: Pre-commit and pytest checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Install dependencies
      run: pip install -r requirements.txt
  

    - name: Run pre-commit checks
      run: pre-commit run --all-files

    - name: Run pytest
      run: pytest
